### ISSUE TITLE
Priority: Convert existing `man/*.Rd` old school help files into new school help files using `roxygen2`

### ISSUE THREAD

**Issue by arrismo** [rudeboybert/SpatialEpi#23]
- [x] Create a new branch and pull request
- [x] Convert **ONE** function to the updated roxygen2 format
- [x] Tag Albert when done so he can review
- [x]  Wait for @rudeboybert  to fix issue

**Comment by arrismo** [comment]
Next steps: 
- [ ] Wait for Albert's green light to continue

**Comment by rudeboybert** [comment]
Like I said on Slack, can you now roxygenize 5-7 more functions in a new PR? Try to pick out 5-7 functions that look non-complex and simple

**Comment by arrismo** [comment]
Notes for Stand Up: 
Need help converting the `NAMESPACE` file using roxygen 
When I used the directions from here https://r-pkgs.org/namespace.html it caused more problems so I removed it
