### ISSUE TITLE
Manuscript Error

### ISSUE THREAD

**Issue by arrismo** [rudeboybert/SpatialEpi#32]
`Quitting from lines 139-144 (Manuscript.Rmd) 
Error in if (plot) { : argument is not interpretable as logical
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> kulldorff
Execution halted`

**Comment by rudeboybert** [comment]
Heads up @arrismo, I commented out a few sections of code b/c I couldn't find a fast fix for them. They're marked with `# Heads up Arris I temporarily commented this out`.

I did this in the interest of getting the manuscripts to knit ASAP. Spent 20 minutes to see if you can get them fixed; if not leave them commented out. 

As you said, the references are also needed.
