### ISSUE TITLE
New GDAL/PROJ require UTM zone

### ISSUE THREAD

**Issue by rsbivand** [rudeboybert/SpatialEpi#34]
In revdeps **SpatialEpi** fails in `mapvariable()` in ?EBpostthresh: 
[00check.log](https://github.com/rudeboybert/SpatialEpi/files/7097961/00check.log)
because `"+proj=utm"` has never been valid without a zone, and now a zone number is required. See also https://github.com/GlobalEcologyLab/poems/issues/1, https://github.com/PredictiveEcology/NetLogoR/issues/43:
```
> slot(scotland$spatial.polygon, "proj4string")
Coordinate Reference System:
Deprecated Proj.4 representation: +proj=utm 
Warning message:
In wkt(x) : CRS object has no comment
```

**Comment by rudeboybert** [comment]
Thanks for the heads up @rsbivand, I'll address this at our next update

**Comment by rsbivand** [comment]
This is caused by https://github.com/OSGeo/PROJ/pull/2672 from https://github.com/OSGeo/PROJ/issues/2671 and applies in PROJ >= 8, probably backported to 8.0.1 and applies in 8.1.*.

**Comment by rudeboybert** [comment]
Based on https://github.com/GlobalEcologyLab/poems/issues/1 use `crs = "+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"`
