### ISSUE TITLE
The expected calculation method in the SpatialEpi package

### ISSUE THREAD

**Issue by colourfulmww** [rudeboybert/SpatialEpi#39]
Hi, I am curious about the formula for the expected number of incidences in the SpatialEpi package.
I would be honored if I could get your reply.

**Comment by rudeboybert** [comment]
Sorry for the delay in replying. We used direct/internal standardization, which you can see in Table 2 here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3406211/

1. compute the strata specific rates for the study region as a whole
2. for each region, multiply the strata specific rates times the population size for the strata to get expected disease counts for that strata for that region
3. sum expected disease counts for that strata for that region, to get expected counts for each region.
